<!DOCTYPE html>
<html lang="en">
<head>
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Alenthea Design Co.",
  "image" : "https://alenthea.com/images/alentheaFullLogo_light.svg",
  "telephone" : "7063665561",
  "email" : "cody@alenthea.com",
  "address" : {
    "@type" : "PostalAddress",
    "addressLocality" : "Columbus",
	"addressRegion" : "Georgia",
	"addressCountry" : "United States",
	"postalCode" : "31909"
  },
  "url" : "https://alenthea.com/",
  "priceRange" : "$$"
}
</script>
<script type="application/ld+json">
    {
	  "@context": "https://schema.org",
	  "@type": "BreadcrumbList",
  		"itemListElement": [{
          "@type": "ListItem",
          "position": 1,
          "name": "Alenthea Design Co",
          "item": "http://alenthea.com/index.php"
  	    }]
	}
</script>
<link rel="preconnect" href="https://fonts.gstatic.com">
<link rel="preconnect" href="https://www.googletagmanager.com/gtag/js?id=UA-157506747-1">
<!-- <script async rel="preconnect" src="https://www.googletagmanager.com/gtag/js?id=UA-157506747-1"></script> -->
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-157506747-1');
</script>
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<meta charset="utf-8">
<title>Web Design, Digital Marketing, and SEO - Columbus, GA | Alenthea Design Co.</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="/style.css" rel="stylesheet" type="text/css">
<link href="/index.css" rel="stylesheet" type="text/css">
<meta name="description" content="We are a full-service design agency operating in Columbus, GA. We specialize in Web Design, Digital Marketing, logos, and Branding. Ask about out low cost hosting options!" />
<meta name="keywords" content="Web, Design, Logos, Branding, Online, Marketing, Development" />
<!-- <meta http-equiv="refresh" content="1"> -->
<!-- <base href="http://www.alenthea.com/index.html"> -->
<!-- <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet"> -->
</head>
<body>
	<?php include 'sections/header.php';?>
	<main>
		<section id="heroImage" class="flex center">
			<img src="/images/alentheaFullLogo.svg" alt="Alenthea Logo">
		</section>
		<section id="openingPitch">
		<h1>Alenthea is a Digital Design Agency based in Columbus, Ga.</h1>
		<p class="homepage-pitch font-two">We specialize in Website Design, S.E.O., Digital Marketing, Logos, Branding, and E-Commerce.</p>
		<p class="homepage-pitch font-two">
			Our Hand-Crafted solutions  are uniquely developed with each individual client for a product that stands 
			out from the competition and delivers Complete Satisfaction.
	</p>
	</section>
		<section class="flex row center full wrap" id="services">
			<section id="webDesign" class="flex column center serviceTile light">
			<div class="flex column center serviceTile light container">
				<div class="flex medium center serviceIconContainer">
					<picture>
						<source media="(max-width: 800px)" srcset="/images/webDev-darkest.svg">
						<source media="(min-width: 800px)" srcset="/images/webDev-light.svg">
						<img src="/images/webDev-dark.svg" alt="Web Design">
					</picture>
				</div>
				<div class="serviceTileContent flex column center">
					<h1>Web Design</h1>
					<p>Enjoy a responsive and beautiful website custom built for all devices.</p>	
					<a href="/services/columbus-ga-web-design" class="button">View More</a>
				</div>
	</div>
			</section>
			<section id="ecommerce" class="flex column center serviceTile light">
			<div class="flex column center serviceTile light container">
				<div class="flex medium center serviceIconContainer">
					<picture>
						<source media="(max-width: 800px)" srcset="/images/ecommerce-darkest.svg">
						<source media="(min-width: 800px)" srcset="/images/ecommerce-light.svg">
						<img src="/images/ecommerce-light.svg" alt="E-Commerce">
					</picture>
				</div>
				<div class="serviceTileContent flex column center">
					<h1>E-Commerce</h1>
					<p>Grow your customer base and reach new potential.</p>	
					<a href="/services/ecommerce" class="button">View More</a>
				</div>
			</div>
			</section>
			<section id="onlineMarketing" class="flex column center serviceTile light">
			<div class="flex column center serviceTile light container">
				<div class="flex medium center serviceIconContainer">
					<picture>
						<source media="(max-width: 800px)" srcset="/images/onlineMarketing-darkest.svg">
						<source media="(min-width: 800px)" srcset="/images/onlineMarketing-light.svg">
						<img src="/images/onlineMarketing-darkest.svg" alt="Online Marketing">
					</picture>
				</div>
					<div class="serviceTileContent flex column center">
						<h1>Online Marketing</h1>
						<p>Spread awareness for your products or brand.</p>	
						<a href="/services/digital-marketing-columbus-ga" class="button">View More</a>
					</div>
				</div>
			</section>
			<section id="logosBranding" class="flex column center serviceTile light">
				<div class="flex column center serviceTile light container">
					<div class="flex medium center serviceIconContainer">
						<picture>
							<source media="(max-width: 800px)" srcset="/images/logoBranding-darkest.svg">
							<source media="(min-width: 800px)" srcset="/images/logoBranding-light.svg">
							<img src="/images/logoBranding-light.svg" alt="Logos & Branding">
						</picture>
					</div>
					<div class="serviceTileContent flex column center">
						<h1>Logos & Branding</h1>
						<p>Give your brand a new, fresh, and timeless appearance.</p>	
						<a href="/services/branding" class="button">View More</a>
					</div>
				</div>
			</section>
		</section>

	<section class="flex center row light" id="missionBanner">
		<img src="/images/alentheaFullLogoDark.svg" alt="Alenthea Design Company Logo">
		<h1>Our Mission Is To Help Our Clients Realize Their Dreams,<br> No Matter How Big Or Small.</h1>
	</section>

	<section class="flex center column" id="webManagement">
		<h1>Need Help With Your Current Website?</h1>
		<h2>We have the perfect plan to fit every budget.</h2>
		<hr>
		<h3>With a Lightning Fast response time we are here for when you need us the most. Stop wasting your time waiting for solutions, let the experts get it done.</h3>
		<section class="flex row space-around center">
			<article class="flex column center">
				<div class="flex center column">
					<h1>Hosting & Support</h1>
					<hr>
					<p>We'll keep your website up and running with real-time monitoring and regular backups.</p>
				</div>
				<div class="flex center column managementHalf">
					<div class="flex center column pricingCont">
						<div class="flex center price">
							<div class="moneySymbol">$</div>
							<div class="serviceCost">25</div>
						</div>	
						<div class="eachMonth">each month</div>
					</div>
					<ul>
						<li>• Server monitoring and Weekly backups.</li>
						<li>• Increase your website's speed and performance.</li>
						<li>• 5 hours of premium support each month.</li>
						<li>• Guaranteed 99.9% Website Up-time.</li>
					</ul>
					<button><a href="/contact.php">Learn More</a></button>
				</div>
			</article>
			<article class="flex column center" id="middleManagement">
				<div class="flex center column">
					<h1>Search Engine Optimization & Content Management</h1>
					<hr>
					<p>Perfect for websites that require extended support with regular content updates.</p>
				</div>
				<div class="flex center column managementHalf">
					<div class="flex center column pricingCont">
						<div class="flex center price">
							<div class="moneySymbol">$</div>
							<div class="serviceCost">70</div>
						</div>	
						<div class="eachMonth">each month</div>
					</div>
					<ul>
						<li>• Monthly S.E.O. monitoring and strategy.</li>
						<li>• Includes 3 free content updates per month.</li>
						<li>• 20 hours of premium support each month.</li>
						<li>• Monthly analytics review and strategy.</li>
					</ul>
					<button><a href="/contact.php">Learn More</a></button>
				</div>
			</article>
			<article class="flex column center">
				<div>
					<div class="flex center column">
						<h1>Ecommerce & Marketing</h1>
						<hr>
						<p>Content management of your online store and associated marketing campaigns.</p>
					</div>
				</div>
				<div class="flex center column managementHalf">
					<div class="flex center column pricingCont">
						<div class="flex center price">
							<div class="moneySymbol">$</div>
							<div class="serviceCost">120</div>
						</div>	
						<div class="eachMonth">each month</div>
					</div>
					<ul>
						<li>• 20 hours of premium support each month.</li>
						<li>• S.E.O. Monitoring and Optimization.</li>
						<li>• Server monitoring and Weekly backups.</li>
						<li>• 24/7 Emergency Phone Support.</li>
					</ul>
					<button><a href="/contact.php">Learn More</a></button>
				</div>
			</article>
		</section>
	</section>

	</main>
	<?php include 'sections/contact.php';?>
	<?php include 'sections/footer.php';?>

</body>
</html>