<!doctype html>
<html lang="en">
<head>

<link rel="canonical" href="/" />
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Alenthea Design Co.",
  "telephone" : "7068880976",
  "email" : "cody@alenthea.com",
  "address" : {
    "@type" : "PostalAddress",
    "addressLocality" : "Columbus",
    "addressRegion" : "Georgia",
    "addressCountry" : "United States",
    "postalCode" : "31909"
  },
  "url" : "https://alenthea.com/"
}
</script>
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-157506747-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-157506747-1');
</script>

	<script type="application/ld+json">
		{
		  "@context": "https://schema.org",
		  "@type": "Organization",
		  "url": "http://www.alenthea.com",
		  "logo": "http://www.alenthea.com/images/alentheaFullDark.png",
		  "areaServed": "Columbus, Georgia, Alabama, Atlanta",
		  "brand": "Alenthea, Alenthea Design Co"
		}"
		</script>
        <script type="application/ld+json">
        {
		  "@context": "https://schema.org",
		  "@type": "BreadcrumbList",
  			"itemListElement": [{
         	  "@type": "ListItem",
          	  "position": 1,
         	  "name": "Alenthea Design Co",
         	  "item": "http://alenthea.com/index.php"
  	    	}]
		}
        
		</script>
		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->

		<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<meta charset="utf-8">
<title>Web Design, Digital Marketing, and SEO - Columbus, GA | Alenthea Design Co.</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="/style.css" rel="stylesheet" type="text/css">
<link href="/index.css" rel="stylesheet" type="text/css">
<meta name="description" content="We are a full-service design agency operating in Columbus, GA. We specialize in Web Design, Digital Marketing, logos, and Branding. Check out our our low to no cost hosting options." />
<meta name="keywords" content="Web, Design, Logos, Branding, Online, Marketing, Development" />
<!-- <meta http-equiv="refresh" content="1"> -->
<!-- <base href="http://www.alenthea.com/index.html"> -->

<!-- <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet"> -->

</head>

<body>
	<?php include 'sections/header.php';?>
	<main>
		<section id="heroImage" class="flex center">
			<img src="/images/alentheaFullLogo.svg" alt="Alenthea Logo">
		</section>
		<section id="openingPitch">
		<h1>Alenthea is a Digital Design Agency based in Columbus, Ga.</h1>
		<h2 id="homepage-pitch" class="font-two">We specialize in Website Design, S.E.O., Digital Marketing, Logos, Branding, and E-Commerce.</h2>
		<h2 id="homepage-pitch" class="font-two">
			Our Hand-Crafted solutions  are uniquely developed with each individual client for a product that stands 
			out from the competition and delivers Complete Satisfaction.
		</h2>
	</section>
		<section class="flex row center full wrap" id="services">
			<section id="webDesign" class="flex column center serviceTile light">
				<div class="flex medium center serviceIconContainer">
					<picture>
						<source media="(max-width: 800px)" srcset="/images/webDev-darkest.svg">
						<source media="(min-width: 800px)" srcset="/images/webDev-light.svg">
						<img src="/images/webDev-dark.svg" alt="Web Design">
					</picture>
				</div>
				<div class="serviceTileContent flex column center">
					<h1>Web Design</h1>
					<p>Mobile friendly, responsive, and beautiful across all devices.</p>	
					<a href="/pages/columbus-ga-web-design" class="button">View More</a>
				</div>
			</section>
			<section id="ecommerce" class="flex column center serviceTile light">
				<div class="flex medium center serviceIconContainer">
					<picture>
						<source media="(max-width: 800px)" srcset="/images/ecommerce-darkest.svg">
						<source media="(min-width: 800px)" srcset="/images/ecommerce-light.svg">
						<img src="/images/ecommerce-light.svg" alt="E-Commerce">
					</picture>
				</div>
				<div class="serviceTileContent flex column center">
					<h1>E-Commerce</h1>
					<p>Grow your customer base and reach new potential.</p>	
					<a href="/pages/ecommerce" class="button">View More</a>
				</div>
			</section>
			<section id="onlineMarketing" class="flex column center serviceTile light">
				<div class="flex medium center serviceIconContainer">
					<picture>
						<source media="(max-width: 800px)" srcset="/images/onlineMarketing-darkest.svg">
						<source media="(min-width: 800px)" srcset="/images/onlineMarketing-light.svg">
						<img src="/images/onlineMarketing-darkest.svg" alt="Online Marketing">
					</picture>
				</div>
				<div class="serviceTileContent flex column center">
					<h1>Online Marketing</h1>
					<p>Spread awareness for your products or brand.</p>	
					<a href="/pages/marketing" class="button">View More</a>
				</div>
			</section>
			<section id="logosBranding" class="flex column center serviceTile light">
				<div class="flex medium center serviceIconContainer">
					<picture>
						<source media="(max-width: 800px)" srcset="/images/logoBranding-darkest.svg">
						<source media="(min-width: 800px)" srcset="/images/logoBranding-light.svg">
						<img src="/images/logoBranding-light.svg" alt="Logos & Branding">
					</picture>
				</div>
				<div class="serviceTileContent flex column center">
					<h1>Logos & Branding</h1>
					<p>Give your brand a new, fresh, and timeless appearance.</p>	
					<a href="/pages/branding" class="button">View More</a>
				</div>
			</section>
		</section>

	


	<section class="flex center row light" id="missionBanner">
		<img src="/images/alentheaFullLogoDark.svg" alt="Alenthea Design Company Logo">
		<h3>Our Mission Is To Help Our Clients Realize Their Dreams,<br> No Matter How Big Or Small.</h3>
	</section>




	<article id="ourWork" class="flex full center column">
		<h1>Our Work</h1>
		<div class="flex center row">
		<section class="flex column center">
			<img src="/images/12407.png">
			<h1>The Wade Companies</h1>
			<h2>Website Design</h2>
		</section>
		<section class="flex column center">
			<img src="/images/businessCard Tile 1.png">
			<h1>All Wood Work</h1>
			<h2>Branding & Identity</h2>
		</section>
		<section class="flex column center">
			<img src="/images/buddybaked.svg">
			<h1>Buddy Baked</h1>
			<h2>Marketing & E-Commerce</h2>
		</section>
	</div>
	</article>





		<!-- <section id="goals" class="flex center column">
			<h2>Achieve Your Goals</h2>
			<div class="flex row center">
				<p>Generate more leads and market your services locally and nationally. Promote trust in your brand and show your expertise.</p>
				<p>Rank higher in organic search results and make yourself discoverable on the web. Increase your presence in local search.</p>
				<p>Refresh your brand identity and maintain a modern appearance in today’s ever evolving market.</p>
			</div>
		</section> -->



	</main>
	<?php include 'sections/contact.php';?>
	<a href="https://twitter.com/alentheac?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-screen-name="false" data-show-count="false">Follow @alenthea2</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>	
	<?php include 'sections/footer.php';?>

</body>

	
</html>